In [1]:
import numpy as np

In [2]:
A = np.array ([
    [0.,  2,  0, 1],
    [2,   2,  3, 2],
    [4,  -3,  0, 1],
    [6,   1, -6, 1]
])
print (A)

[[ 0.  2.  0.  1.]
 [ 2.  2.  3.  2.]
 [ 4. -3.  0.  1.]
 [ 6.  1. -6.  1.]]


In [3]:
b = np.array  ([
    [ 0.],
    [-2 ],
    [-7 ],
    [ 6 ]
])
print (b)

[[ 0.]
 [-2.]
 [-7.]
 [ 6.]]


In [4]:
M = np.concatenate ((A, b), axis = 1)
print (M)

[[ 0.  2.  0.  1.  0.]
 [ 2.  2.  3.  2. -2.]
 [ 4. -3.  0.  1. -7.]
 [ 6.  1. -6.  1.  6.]]


In [5]:
P = np.array ([
    [0., 0, 0, 1],
    [0 , 1, 0, 0],
    [0 , 0, 1, 0],
    [1 , 0, 0, 0]
])
print (P)

[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]


In [6]:
M = P @ M
print (M)

[[ 6.  1. -6.  1.  6.]
 [ 2.  2.  3.  2. -2.]
 [ 4. -3.  0.  1. -7.]
 [ 0.  2.  0.  1.  0.]]


In [7]:
n = M.shape [0]
print (n)

4


In [8]:
# Gauss
print (np.round (M, 5))
for i in range (n):
    for k in range (i + 1, n):
        M [k] = M [k] - M [k, i] / M [i, i] * M [i]
        print (np.round (M, 5))

[[ 6.  1. -6.  1.  6.]
 [ 2.  2.  3.  2. -2.]
 [ 4. -3.  0.  1. -7.]
 [ 0.  2.  0.  1.  0.]]
[[ 6.       1.      -6.       1.       6.     ]
 [ 0.       1.66667  5.       1.66667 -4.     ]
 [ 4.      -3.       0.       1.      -7.     ]
 [ 0.       2.       0.       1.       0.     ]]
[[  6.        1.       -6.        1.        6.     ]
 [  0.        1.66667   5.        1.66667  -4.     ]
 [  0.       -3.66667   4.        0.33333 -11.     ]
 [  0.        2.        0.        1.        0.     ]]
[[  6.        1.       -6.        1.        6.     ]
 [  0.        1.66667   5.        1.66667  -4.     ]
 [  0.       -3.66667   4.        0.33333 -11.     ]
 [  0.        2.        0.        1.        0.     ]]
[[  6.        1.       -6.        1.        6.     ]
 [  0.        1.66667   5.        1.66667  -4.     ]
 [  0.        0.       15.        4.      -19.8    ]
 [  0.        2.        0.        1.        0.     ]]
[[  6.        1.       -6.        1.        6.     ]
 [  0.        1.66667 

In [9]:
# Jordan
print (np.round (M, 5))
for i in range (n - 1, 0, -1):
    for k in range (i - 1, -1, -1):
        M [k] = M [k] - M [k, i] / M [i, i] * M [i]
        print (np.round (M, 5))

[[  6.        1.       -6.        1.        6.     ]
 [  0.        1.66667   5.        1.66667  -4.     ]
 [  0.        0.       15.        4.      -19.8    ]
 [  0.        0.        0.        0.6      -3.12   ]]
[[ 6.       1.      -6.       1.       6.     ]
 [ 0.       1.66667  5.       1.66667 -4.     ]
 [ 0.       0.      15.       0.       1.     ]
 [ 0.       0.       0.       0.6     -3.12   ]]
[[ 6.       1.      -6.       1.       6.     ]
 [ 0.       1.66667  5.      -0.       4.66667]
 [ 0.       0.      15.       0.       1.     ]
 [ 0.       0.       0.       0.6     -3.12   ]]
[[ 6.       1.      -6.       0.      11.2    ]
 [ 0.       1.66667  5.      -0.       4.66667]
 [ 0.       0.      15.       0.       1.     ]
 [ 0.       0.       0.       0.6     -3.12   ]]
[[ 6.       1.      -6.       0.      11.2    ]
 [ 0.       1.66667  0.      -0.       4.33333]
 [ 0.       0.      15.       0.       1.     ]
 [ 0.       0.       0.       0.6     -3.12   ]]
[[ 6.       1. 

In [10]:
# Einheitsmatrix erzeugen
for i in range (n):
    M [i] = M[i] / M [i, i]
print (np.round (M, 5))

[[ 1.       0.       0.       0.       1.5    ]
 [ 0.       1.       0.      -0.       2.6    ]
 [ 0.       0.       1.       0.       0.06667]
 [ 0.       0.       0.       1.      -5.2    ]]


In [11]:
x = M [0:4, 4:5]
print (x)

[[ 1.5       ]
 [ 2.6       ]
 [ 0.06666667]
 [-5.2       ]]


In [12]:
print (A @ x)

[[ 8.8817842e-16]
 [-2.0000000e+00]
 [-7.0000000e+00]
 [ 6.0000000e+00]]


In [13]:
print (b)

[[ 0.]
 [-2.]
 [-7.]
 [ 6.]]
