## LU-Zerlegung Gleichungssystem lösen

In [7]:
import numpy as np
import numpy.linalg as la

A = np.array ([
    [0, 1, 1],
    [1, 2, 1],
    [2, 7, 9]
])
b = np.array([
    [0],
    [0],
    [4]
])
P = np.array([
    [0, 0, 1],
    [0, 1, 0],
    [1, 0, 0]
])

A = P @ A
b = P @ b

E21 = np.array([
    [1, 0, 0],
    [-1/2, 1, 0],
    [0, 0, 1]
])
E32 = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 2/3, 1]
])

R = E32 @ E21 @ A
L = la.inv(E21) @ la.inv(E32)

L @ R

y = np.array([
    [4],
    [-2],
    [-4/3]
])

L @ y

[[0 1 1]
 [1 2 1]
 [2 7 9]]
[[0]
 [0]
 [4]]


array([[4.],
       [0.],
       [0.]])

In [14]:
import numpy as np

M = np.array([
    [6., -1, -1, 4],
    [1, 1, 10, -6],
    [2, -1, 1, -2]
])

M[1] = M[1] - M[0] / 6
M[2] = M[2] - M[0] / 3

M[1] = M[1] - M[2] * 10
M[0] = M[0] + M[2]
M[0] = M[0] + M[1]
M[0] = M[0] / 6

print(M)

[[ 1  0  0  4]
 [ 0  1  0 24]
 [ 0  0  1 -3]]
