## LU-Zerlegung Gleichungssystem lösen

In [7]:
import numpy as np
import numpy.linalg as la

A = np.array ([
    [0, 1, 1],
    [1, 2, 1],
    [2, 7, 9]
])
b = np.array([
    [0],
    [0],
    [4]
])
P = np.array([
    [0, 0, 1],
    [0, 1, 0],
    [1, 0, 0]
])

A = P @ A
b = P @ b

E21 = np.array([
    [1, 0, 0],
    [-1/2, 1, 0],
    [0, 0, 1]
])
E32 = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 2/3, 1]
])

R = E32 @ E21 @ A
L = la.inv(E21) @ la.inv(E32)

L @ R

y = np.array([
    [4],
    [-2],
    [-4/3]
])

L @ y

[[0 1 1]
 [1 2 1]
 [2 7 9]]
[[0]
 [0]
 [4]]


array([[4.],
       [0.],
       [0.]])

## Gauss - Jordan Zerlegung

In [19]:
import numpy as np

M = np.array([
    [6., -1, -1, 4],
    [1, 1, 10, -6],
    [2, -1, 1, -2]
])

M[1] = M[1] - M[0] / 6
M[2] = M[2] - M[0] / 3
M[2] = M[2] - M[2, 1] / M[1, 1] * M[1]

M[1] = M[1] - M[1, 2] / M[2, 2] * M[2]
M[0] = M[0] - M[0, 2] / M[2, 2] * M[2]
M[0] = M[0] - M[0, 1] / M[1, 1] * M[1]

M[0] = M[0] / M[0, 0]
M[1] = M[1] / M[1, 1]
M[2] = M[2] / M[2, 2]

print(np.round(M, 5))

[[ 1.  0.  0.  1.]
 [ 0.  1.  0.  3.]
 [ 0.  0.  1. -1.]]


In [20]:
import numpy as np

M = np.array([
    [0., 2, 0, 1, 0],
    [2, 2, 3, 2, -2],
    [4, -3, 0, 1, -7],
    [6, 1, -6, 1, 6]
])
P = np.array([
    [0, 0, 0, 1],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [1, 0, 0, 0]
])
M = M @ P

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 5)