In [1]:
import numpy as np

F (also Funktionsmatrix) definieren - Wichtig zu beachten, x ist ein Vektor und die Funktion ist auf zwei Variabeln eingestellt, ansonsten müsste noch auf ein x3 erweitert werden. x2 ist in diesem Fall der Y Wert

In [15]:
def F (x):
    x1 = x [0, 0]
    x2 = x [1, 0]
    # Untenstehend F1 = x-y+1
    F1 = x1-x2+1
    # Untenstehend F2 = x^2 - y - 1
    F2 = x1**2-x2-1
    return np.array ([[F1], [F2]])

x0 Definieren

In [21]:
x0 = np.array ([[-2.0], [-1.0]])
print (x0)

[[-2.]
 [-1.]]


In [22]:
F (x0)

array([[0.],
       [4.]])

Jacobi Matrix definieren - hier auch wieder gleiches Spiel, x1 = x , x2 = y, alles weitere müsste noch nacherfasst werden. F12 ist erste Zeile, zweite Spalte.

In [23]:
def J (x):
    x1 = x [0, 0]
    x2 = x [1, 0]
    F11 = 1
    F12 = -1
    F21 = 2*x1
    F22 = -1
    return np.array ([[F11, F12], [F21, F22]])

In [24]:
J (x0)

array([[ 1., -1.],
       [-4., -1.]])

Fehler definieren und durchlaufen lassen

In [25]:
xk = x0
eps = 5E-6
while 1:
    dx = np.linalg.solve (J (xk), F (xk))
    xk = xk - dx
    print (xk.T)
    if np.sqrt (dx.T @ dx) < eps:
        break

[[-1.2 -0.2]]
[[-1.01176471 -0.01176471]]
[[-1.00004578e+00 -4.57770657e-05]]
[[-1.00000000e+00 -6.98491959e-10]]
[[-1.00000000e+00 -2.87313576e-17]]


In [2]:
A = np.array([
    [20,12],
    [10,12]
])
b = np.array([
    [6],
    [4]
])
np.linalg.solve(A,b)

array([[0.2       ],
       [0.16666667]])