In [1]:
import numpy as np

In [12]:
def f (x):
    return np.e**-x**2

In [13]:
a = -1

In [14]:
b = 2

In [15]:
def Rechteck (f, a, b, n):
    h = (b - a) / n
    x = np.linspace (a, b, n + 1)
    y = f (x)
    return h * np.sum (y [:-1])

In [16]:
def Trapez (f, a, b, n):
    h = (b - a) / n
    x = np.linspace (a, b, n + 1)
    y = f (x)
    return h * ((y [0] + y [-1]) / 2 + np.sum (y [1:-1]))

In [17]:
def Simpson (f, a, b, N):
    n = N // 2
    N = 2 * n
    h = (b - a) / N
    x = np.linspace (a, b, N + 1)
    y = f (x)
    return (b - a) / (6 * n) * (y [0] + 4 * np.sum (y [1:-1:2]) + 2 * np.sum (y [2:-1:2]) + y [-1])

In [23]:
Simpson (f, a, b, 4)

1.6349736115153202

In [36]:
Simpson (f, a, b, 100) - 1

3.3823588374559677e-10

In [37]:
Simpson (f, a, b, 1000) - 1

3.375077994860476e-14

In [25]:
a = np.linspace (0, 10, 11)
print (a)
print (a [0])
print (a [1:-1:2])
print (a [2:-1:2])
print (a [-1])

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
0.0
[1. 3. 5. 7. 9.]
[2. 4. 6. 8.]
10.0


In [7]:
Rechteck (f, a, b, 10)

0.9194031700146124

In [8]:
Rechteck (f, a, b, 100)

0.9921254566056329

In [9]:
Rechteck (f, a, b, 1000)

0.9992143962198358

In [18]:
Trapez (f, a, b, 32)

1.6283128993750746

In [11]:
Trapez (f, a, b, 100)

0.9999794382396073

In [12]:
Trapez (f, a, b, 1000)

0.9999997943832332

In [13]:
def g (x):
    return x ** 2

In [14]:
Trapez (g, 0, 1, 2887)

0.3333333533298884

In [15]:
def h (x):
    return np.exp (- x ** 2)

In [16]:
Trapez (h, -1, 2, 100)

1.6288448461358307