# Übung Prüfungsablauf H22 - Lösung
**20. Dezember 2022**

## Informationen zur Prüfung
### Dauer: 
120 Min


### Total mögliche Punktzahl:
88 Punkte


### Erlaubte Hilfsmittel
Die Prüfung ist "Open Book". Erlaubt sind folgende Mittel:
- Vorlesungsskript und gelöste Übungen
- Persönliche Zusammenfassung
- Python Standardbibliothek - https://docs.python.org/3/library/index.html
- NumPy Dokumentation - https://numpy.org/doc/
- Pandas Dokumentation - https://pandas.pydata.org/pandas-docs/stable/
- Matplotlib Dokumentation - https://matplotlib.org
- Seaborn Dokumentation - https://seaborn.pydata.org


### Nicht erlaubt sind:
- Bezug fremder Hilfe, oder Hilfe leisten (z.B. Ihre Ergebnisse teilen, Tipps geben, etc.)
- Kommunikation mit Dritten während der Prüfung
- Internetrecherche, abgesehen von den oben ausdrücklich erlaubten Seiten
- Jede andere, nicht explizit erwähnte, unredliche Handlung


### Instruktionen
- Die Aufgaben können in beliebiger Reihenfolge gelöst werden
- Auch Teillösungen werden bewertet
- Fügen Sie die Lösung direkt unterhalb der Fragen ein
- Speichern Sie die Prüfungsdatei mit Ihren Lösungen unter Verwendung folgender Namenskonvention: _**Nachname_Vorname_Uebung_Pruefungsablauf.ipynb**_
- Laden Sie ihre Lösung fristgerecht in Ilias hoch
- Falls die Abgabe wider Erwarten über Ilias nicht möglich, senden Sie die gelösten Aufgaben von Ihrer offiziellen HSLU-E-Mail-Adresse an <a href='mailto:philipp.toggweiler@hslu.ch'>philipp.toggweiler@hslu.ch</a>

<br>

<br>

## Redlichkeitsbedingungen
**Mit der Absolvierung der Prüfung bestätige ich, dass ich:**
- die Prüfungen alleine und ohne unerlaubte fremde Hilfe absolviert habe,
- die Lösungen und Resultate selbst hergeleitet habe,
- keine anderen als die für die entsprechende Prüfung ausdrücklich vorgesehenen Hilfsmittel benutzt habe,
- keine unerlaubte Kommunikation mit Dritten während der Prüfung geführt habe

Bei Unredlichkeiten gilt der Artikel 39 der Studienordnung für Ausbildung an der Hochschule Luzern, FH Zentralschweiz (Nr. 521).

&nbsp;

&nbsp;
<font color='red'>_**Datum, Name und Vorname**_</font>

20.12.2022, Schmid Timon

&nbsp;

# Aufgabe 1 (18 Punkte)
Jedes Buch auf der Welt hat eine eindeutige ISBN (internationale Standardbuchnummer). Die letzte Ziffer ist die «Prüfsumme». Mit ihr kann die Korrektheit der ISBN überprüft werden.

Eine ISBN-13 hat 13 Ziffern. Die «Prüfsumme», d.h. die letzte Ziffer, wird wie folgt berechnet:

Wir nehmen die ersten 12 Ziffern und multiplizieren jede einzelne abwechselnd mit 1 oder 3. Dann wird die Summe durch 10 geteilt und der Rest ermittelt. Dieser Rest ist eine Ziffer zwischen 0 und 9. Wir subtrahieren diesen Rest von 10 und erhalten die gesuchte «Prüfsumme», und somit die letzte Ziffer der ISBN-13.


#### Beispiel
Wir nehmen die ISBN-13 eines Buches: 978-0-262-03800-3

Nun gehen wir die ersten 12 Ziffern durch und multiplizieren jede abwechselnd mit 1 oder 3 und bilden die Summe:
```
9 + 7*3 + 8 + 0*3 + 2 + 6*3 + 2 + 0*3 + 3 + 8*3 + 0 + 0*3 = 87
```

Die Summe ist 87.
Wir können diese durch 10 teilen und erhalten den Rest 7.
Die Prüfsumme erhalten wir schliesslich, indem wir 10 – 7 = 3 berechnen.

#### Ihre Aufgabe
Schreiben Sie eine Funktion `validate_isbn13`, die eine ISBN-13 (ein String) als Argument annimmt und entweder `True` oder `False` zurückgibt, um anzuzeigen, ob es sich um eine gültige ISBN-13 handelt oder nicht.



In [15]:
def validate_isbn13(isbn_13: str):
    numbers = list(map(lambda number: int(number), [*isbn_13.replace('-', '')]))
    check_number = numbers.pop()
    index = 0
    sum = 0
    for number in numbers:
        if index % 2:
            sum += number * 3
        else:
            sum += number
        index += 1
    
    calculated_check_number = 10 - (sum % 10)
    return check_number == calculated_check_number
        
validate_isbn13('978-0-262-03800-3')

True


&nbsp;
# Aufgabe 2 (8 Punkte)
a) Erzeugen Sie einen (4 x 5)-Array welcher die geraden Ganzzahlwerte 2 bis 40 (inkl.) enthält und geben Sie den erzeugten Array aus.

b) Erzeugen Sie mittels broadcasting einen (4 x 5)-Array, der die Quadratzahlen des Arrays aus Aufgabe a) enthält. Geben Sie den erzeugten Array aus.

c) Selektieren Sie mittels Slicing die 2. und 5. Spalte des Arrays, welcher die Quadratzahlen aus Aufgabe b) enthält und geben Sie das Resultat aus.<br>
NB: Die Spalte 1 hat den Index 0

d) Berechnen Sie die Durchschnittswerte jeder Spalte des Arrays, welcher die Quadratzahlen aus Aufgabe b) enthält und geben Sie das Resultat aus.

In [3]:
import numpy as np

# a)
a = np.arange(2, 41, 2).reshape(4, 5)
print(a)

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]]


In [4]:
# b)
b = a ** 2
print(b)

[[   4   16   36   64  100]
 [ 144  196  256  324  400]
 [ 484  576  676  784  900]
 [1024 1156 1296 1444 1600]]


In [7]:
# c)
c = b[:, 1:5:3]
print(c)

[[  16  100]
 [ 196  400]
 [ 576  900]
 [1156 1600]]


In [ ]:
# d)



&nbsp;
# Aufgabe 3 (22 Punkte)
Implementieren Sie die Klassen `Rectangle` und `Square` mit folgenden Eigenschaften:
* Beim Erzeugen eines `Rectangle`-Objekts soll die Länge und Breite des Rechtecks übergeben werden. Länge und Breite können jederzeit im Objekt geändert werden, dürfen jedoch nicht negativ oder gleich 0 sein.
* Die `perimeter`-Methode, gibt den Umfang zurück.
* Die `area`-Methode, gibt die Fläche zurück.
* Die `__repr__`-Methode, gibt gem. dem aktuellen State z.B.  "Rectangle(length: 5.0, width: 4.5)" aus.
* `Square` erbt von `Rectangle`
* Beim Erzeugen eines `Square`-Objekts soll die Seitenlänge des Qaudrats übergeben werden. Diese kann jederzeit im Objekt geändert werden.
* Die `__repr__`-Methode, gibt entsprechend dem aktuellen State z.B. "Square(length: 2.0)" aus.


Schreiben Sie einen Test, der die Klassen und ihre Methoden polymorph testet.

In [28]:
class Rectangle:

    def __init__(self, width: float, length: float) -> None:
        self.set_width(width)
        self.set_length(length)

    def set_width(self, width: float) -> None:
        if width <= 0:
            raise ValueError('width cannot be negativ or zero')
        self.width = width

    def set_length(self, length: float) -> None:
        if length <= 0:
            raise ValueError('length cannot be negativ or zero')
        self.length = length

    def perimeter(self) -> float:
        return (self.width + self.length) * 2

    def area(self) -> float:
        return self.width * self.length

    def __repr__(self) -> str:
        return f'Rectangle(length: {self.length}, width: {self.width})'

class Square(Rectangle):

    def __init__(self, length: float) -> None:
        super().__init__(length, length)

    def set_length(self, length: float) -> None:
        super().set_length(length)
        super().set_width(length)

    def __repr__(self) -> str:
        return f'Square(length: {self.length})'

rectangle = Rectangle(4.5, 5.0)
assert str(rectangle) == 'Rectangle(length: 5.0, width: 4.5)'

square = Square(2.0)
assert str(square) == 'Square(length: 2.0)'

Square(length: 2.0)


&nbsp;

# Aufgabe 4  (10 Punkte)
a) Erstellen Sie mittels List-Comprehension eine Liste, die 10 zufällige Buchstaben aus dem Bereich ‘a’ – ‘f’ (inklusive) enthält.

Führen Sie dann die folgenden Aufgaben aus und zeigen Sie Ihre Ergebnisse an:

b) Sortieren Sie die Liste in absteigender Reihenfolge, ohne dabei die Ursprungsliste zu verändern.<br>
c)   Sortieren Sie die eindeutigen (d.h. Duplikat freien) Werte in aufsteigender Reihenfolge. Die Ursprungsliste soll dabei nicht modifiziert werden.


In [32]:
# a) 
import random

characters = ['a', 'b', 'c', 'd', 'e', 'f']
random_characters = [characters[random.randint(0, len(characters) - 1)] for number in range(10)]
print(random_characters)


['c', 'b', 'c', 'd', 'd', 'a', 'f', 'f', 'e', 'd']


In [34]:
# b)
print(sorted(random_characters, reverse=True))

['f', 'f', 'e', 'd', 'd', 'd', 'c', 'c', 'b', 'a']
['c', 'b', 'c', 'd', 'd', 'a', 'f', 'f', 'e', 'd']


In [35]:
# c)
sorted(set(random_characters))

['a', 'b', 'c', 'd', 'e', 'f']


&nbsp;
# Aufgabe 5 (22 Punke)
Schere, Stein, Papier (auch als Schnik, Schnak, Schnuk bekannt) - ist ein sowohl bei Kindern als auch bei Erwachsenen beliebtes und weltweit verbreitetes Spiel.

Zwei Spieler wählen je eins der drei möglichen Symbole _Schere_, _Stein_ oder _Papier_ und zeigen dieses dann auf ein Kommando gleichzeitig (schlagartig) mit Hilfe einer ihrer Hände an. Da jedes Symbol gegen ein anderes gewinnen oder verlieren kann, steht immer einer der Spieler als Gewinner fest. Zu Unentschieden kommt es, wenn beide Spieler dasselbe Symbol wählen. Das Spiel wird in diesem Fall wiederholt.  (Quelle: Wikiepedia)

Schreiben Sie ein Programm, das Sentinel gesteuert beliebig oft wiederholt werden kann. Die Spielerin oder der Spieler soll via Prompt aufgefordert werden, ihre Wahl (Schere, Stein oder Papier) einzugeben. Dann wird intern für den Gegenspieler ebenfalls ein zufälliges Symbol ausgewählt und in der Folge der oder die Siegerin, oder das Untentschieden bekannt gebeben. Im Fall von Unentschieden wird nochmals widerholt, bis der oder die Gewinnerin bekannt ist.

In [44]:
import random


options = ['schere', 'stein', 'papier']

def get_player_input() -> str:
    while True:
        player = input('Waehle Schere, Stein oder Papier: ').lower()
        if not options.index(player) == -1:
            return player

while True:
    bot = options[random.randint(0, len(options) - 1)]
    player = get_player_input()
    print(player)
    print(bot)

    if player == bot:
        print('Unentschieden, noch einmal!')
    elif options.index(player) == 0 and options.index(bot) == 2:
        print('Du hast gewonnen!')
    elif options.index(bot) == 0 and options.index(player) == 2:
        print('Du hast verloren!')
    elif options.index(player) > options.index(bot):
        print('Du hast gewonnen!')
    else:
        print('Du hast verloren!')
    

stein
schere
Du hast gewonnen!


ValueError: '' is not in list

&nbsp;

# Aufgabe 6 (8 Punkte)
Gegeben sei das folgende Dictionary:
```
temps = {'Mon': [68, 89], 'Tue': [71, 93], 'Wed': [66, 82], 'Thu': [75, 97], 'Fri': [62, 79]}
```

a) Konvertieren Sie das Dictionary in ein DataFrame mit dem Namen `temperatures` und den benutzerdefinierten Indizes "Low" und "High". Zeigen Sie das DataFrame an.

b) Filtern Sie das DateFrame, so dass nur die Spalten für 'Mon', 'Tue' und 'Wed' ausgegeben werden.

c) Zeigen Sie nur die niedrigsten Temperaturen für jeden Tag an. 

d) Berechnen Sie die Durchschnittstemperatur für jeden Tag.

e) Berechnen Sie die durchschnittlichen Höchst- und Tiefsttemperaturen.

In [48]:
# a)
import pandas as pd

temps = {'Mon': [68, 89], 'Tue': [71, 93], 'Wed': [66, 82], 'Thu': [75, 97], 'Fri': [62, 79]}

temperatures = pd.DataFrame(temps)
temperatures.index = ['Low', 'High']
temperatures

Mon  Tue  Wed  Thu  Fri
Low    68   71   66   75   62
High   89   93   82   97   79

In [53]:
# b)
temperatures.iloc[[0, 1], 0:3]

Mon  Tue  Wed
Low    68   71   66
High   89   93   82

In [54]:
# c)
temperatures.iloc[[0]]

Mon  Tue  Wed  Thu  Fri
Low   68   71   66   75   62

In [55]:
# d)
temperatures.mean()

Mon    78.5
Tue    82.0
Wed    74.0
Thu    86.0
Fri    70.5
dtype: float64

In [56]:
# e)
temperatures.T.mean()


Low     68.4
High    88.0
dtype: float64