In [1]:
import numpy as np
import numpy.linalg as la

In [13]:
X = np.array([
    [1, 1, 1.0],
    [1, 2, 1.0],
    [1, 2, 2.0],
    [1, 1, 2.0]
])
print (X)

[[1. 1. 1.]
 [1. 2. 1.]
 [1. 2. 2.]
 [1. 1. 2.]]


In [14]:
y = np.array([
    [1.0],
    [2.0],
    [3.0],
    [3.0]
])

In [15]:
XTX = X.T @ X
print(XTX)

[[ 4.  6.  6.]
 [ 6. 10.  9.]
 [ 6.  9. 10.]]


<strong>Regressionskoeffizienten</strong>

In [17]:
bHat = la.inv(XTX) @ X.T @ y
print(bHat)

[[-0.75]
 [ 0.5 ]
 [ 1.5 ]]


<strong>Projektionsmatrix P</strong>

In [18]:
P = X @ la.inv(XTX) @ X.T
print(P)

[[ 0.75  0.25 -0.25  0.25]
 [ 0.25  0.75  0.25 -0.25]
 [-0.25  0.25  0.75  0.25]
 [ 0.25 -0.25  0.25  0.75]]


<strong>Residualmatrix Q</strong>

In [21]:
Q = np.identity(len(P)) - P
print(Q)

[[ 0.25 -0.25  0.25 -0.25]
 [-0.25  0.25 -0.25  0.25]
 [ 0.25 -0.25  0.25 -0.25]
 [-0.25  0.25 -0.25  0.25]]


<strong>Zentrierende Matrix M</strong>

In [39]:
M = np.identity(len(P)) - 1/len(P) * np.ones((len(P), len(P)))
print(M)

[[ 0.75 -0.25 -0.25 -0.25]
 [-0.25  0.75 -0.25 -0.25]
 [-0.25 -0.25  0.75 -0.25]
 [-0.25 -0.25 -0.25  0.75]]


<strong>Praedikationsvektor yHat</strong>

In [40]:
yHat = P @ y
print(yHat)

[[1.25]
 [1.75]
 [3.25]
 [2.75]]


<strong>Fehlervektor e</strong>

In [41]:
e = y - yHat
print('y - yHat:\n', e)
e2 = Q @ y
print('Q @ y:\n', e2)

y - yHat:
 [[-0.25]
 [ 0.25]
 [-0.25]
 [ 0.25]]
Q @ y:
 [[-0.25]
 [ 0.25]
 [-0.25]
 [ 0.25]]


<strong>Bestimmtheitsmass R^2</strong>

In [44]:
SQR = y.T @ Q @ y
print(SQR)
SQT = y.T @ M @ y
print(SQT)
R2 = 1 - SQR / SQT
print('R^2:', R2)

[[0.25]]
[[2.75]]
R^2: [[0.90909091]]
