In [1]:
import numpy as np
import numpy.linalg as la

In [2]:
X = np.array ([
    [1, 2, 1.1],
    [1, 2, 1.9],
    [1, 4, 2.0],
    [1, 5, 1.5],
    [1, 7, 2.1]
])
print (X)

[[1.  2.  1.1]
 [1.  2.  1.9]
 [1.  4.  2. ]
 [1.  5.  1.5]
 [1.  7.  2.1]]


In [3]:
b = np.array ([
    [ 93.0],
    [106.0],
    [146.0],
    [140.0],
    [158.0]
])
print (b)

[[ 93.]
 [106.]
 [146.]
 [140.]
 [158.]]


In [4]:
bhat = la.solve (X.T @ X, X.T @ b)
print (bhat)

[[54.77165354]
 [10.04330709]
 [19.56692913]]


In [5]:
yhat = X @ bhat
print (yhat)

[[ 96.38188976]
 [112.03543307]
 [134.07874016]
 [134.33858268]
 [166.16535433]]


In [6]:
e = b - yhat
print (e)

[[-3.38188976]
 [-6.03543307]
 [11.92125984]
 [ 5.66141732]
 [-8.16535433]]


In [7]:
P = X @ la.inv (X.T @ X) @ X.T
print (P)

[[ 0.76946632  0.10804899 -0.03149606  0.35345582 -0.19947507]
 [ 0.10804899  0.70647419  0.40944882 -0.15048119 -0.07349081]
 [-0.03149606  0.40944882  0.35433071  0.02362205  0.24409449]
 [ 0.35345582 -0.15048119  0.02362205  0.45713036  0.31627297]
 [-0.19947507 -0.07349081  0.24409449  0.31627297  0.71259843]]


In [8]:
P @ b

array([[ 96.38188976],
       [112.03543307],
       [134.07874016],
       [134.33858268],
       [166.16535433]])

In [9]:
yhat

array([[ 96.38188976],
       [112.03543307],
       [134.07874016],
       [134.33858268],
       [166.16535433]])

In [10]:
Q = np.eye (5) - X @ la.inv (X.T @ X) @ X.T
print (Q)

[[ 0.23053368 -0.10804899  0.03149606 -0.35345582  0.19947507]
 [-0.10804899  0.29352581 -0.40944882  0.15048119  0.07349081]
 [ 0.03149606 -0.40944882  0.64566929 -0.02362205 -0.24409449]
 [-0.35345582  0.15048119 -0.02362205  0.54286964 -0.31627297]
 [ 0.19947507  0.07349081 -0.24409449 -0.31627297  0.28740157]]


In [11]:
Q @ b

array([[-3.38188976],
       [-6.03543307],
       [11.92125984],
       [ 5.66141732],
       [-8.16535433]])

In [12]:
e

array([[-3.38188976],
       [-6.03543307],
       [11.92125984],
       [ 5.66141732],
       [-8.16535433]])

In [13]:
P

array([[ 0.76946632,  0.10804899, -0.03149606,  0.35345582, -0.19947507],
       [ 0.10804899,  0.70647419,  0.40944882, -0.15048119, -0.07349081],
       [-0.03149606,  0.40944882,  0.35433071,  0.02362205,  0.24409449],
       [ 0.35345582, -0.15048119,  0.02362205,  0.45713036,  0.31627297],
       [-0.19947507, -0.07349081,  0.24409449,  0.31627297,  0.71259843]])

In [14]:
P @ P

array([[ 0.76946632,  0.10804899, -0.03149606,  0.35345582, -0.19947507],
       [ 0.10804899,  0.70647419,  0.40944882, -0.15048119, -0.07349081],
       [-0.03149606,  0.40944882,  0.35433071,  0.02362205,  0.24409449],
       [ 0.35345582, -0.15048119,  0.02362205,  0.45713036,  0.31627297],
       [-0.19947507, -0.07349081,  0.24409449,  0.31627297,  0.71259843]])

In [15]:
Q - Q @ Q

array([[ 1.47104551e-15,  1.66533454e-16,  7.63278329e-17,
         9.43689571e-16,  5.55111512e-17],
       [-2.49800181e-16, -5.55111512e-17,  2.22044605e-16,
         2.49800181e-16,  6.10622664e-16],
       [-4.30211422e-16,  1.66533454e-16,  3.33066907e-16,
        -2.77555756e-17,  5.55111512e-16],
       [ 6.66133815e-16,  4.16333634e-16,  2.60208521e-16,
         3.33066907e-16,  1.11022302e-16],
       [-6.38378239e-16,  4.71844785e-16,  4.44089210e-16,
        -2.77555756e-16,  3.33066907e-16]])

In [16]:
ybar = np.average (b)
print (ybar)

128.6


In [17]:
b

array([[ 93.],
       [106.],
       [146.],
       [140.],
       [158.]])

In [18]:
def SQ (x):
    return x.T @ x

In [19]:
SQT = (b - ybar) .T @ (b - ybar)
print (SQT)

[[3075.2]]


In [20]:
SQ (b - ybar)

array([[3075.2]])

In [21]:
SQE = (yhat - ybar) .T @ (yhat - ybar)
print (SQE)

[[2786.49527559]]


In [22]:
SQ (yhat - ybar)

array([[2786.49527559]])

In [23]:
SQE / SQT

array([[0.90611839]])

In [24]:
SQR = (b - yhat) .T @ (b - yhat)
print (SQR)

[[288.70472441]]


In [25]:
SQ (b - yhat)

array([[288.70472441]])

In [26]:
SQT

array([[3075.2]])

In [27]:
SQE + SQR

array([[3075.2]])