# Formelsammlung Lineare Algebra

In [ ]:
import numpy as np

## Vektorgeometrie

// TODO !!!

## Lineare Gleichungssysteme

### Multiplikation zweier Matrizen

In [5]:
import numpy as np

A = np.array([
    [4, -2, -2, 0],
    [-2, -7, 3, 8],
    [0, 1, -2, -1]
])
B = np.array([
    [4, -5],
    [3, -1],
    [6, 4],
    [0, -3]
])
A @ B

array([[ -2, -26],
       [-11,   5],
       [ -9,  -6]])

### Gleichungssystem anhand einer Koeffizientenmatrix lösen
#### Definition
<strong>A</strong> = Matrix der Koeffizienten<br>
<strong>b</strong> = Matrix der Konstanten

#### Beispiel
<strong>Gleichungssystem:</strong><br>
6x − y −   z =  4<br>
 x + y + 10z = −6<br>
2x − y +   z = −2<br>
<br>
<strong>Erweiterte Koeffizientenmatrix:</strong><br>
\[6, -1, -1|4\]<br>
\[1, 1, 10|-6\]<br>
\[2, -1, 1|-2\]<br>

#### Einsetzen
```python
A = np.array([
    [6, -1, -1],
    [1, 1, 10],
    [2, -1, 1],
])
b = np.array([
    [4],
    [-6],
    [-2],
])
```

#### Lösung
Die funktion ```np.linalg.solve()``` gibt ein Array mit den Werten für \[x, y, z\] zurück.
```python
[[ 1.]
 [ 3.]
 [-1.]]
```

In [ ]:
A = np.array([
    [3, 2, -1],
    [5, 3, 2],
    [3, 1, 3],
])
b = np.array([
    [-15],
    [0],
    [11],
])
x = np.linalg.solve(A, b)
print(x)

[[ 7. -3.]
 [-2.  1.]]
