# 12.5 Erstellen von Arrays aus Bereichen
NumPy bietet optimierte Methoden zum Erstellen von Array's aus Bereichen

## Ganzzahlige Bereiche mit `arange` erstellen

In [1]:
import numpy as np

In [2]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [3]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [4]:
np.arange(10, 1, -2)

array([10,  8,  6,  4,  2])

## Erstellen von linearen Fliesskomma-Bereichen mit `linspace` 
* Der **Endwert ist im Array enthalten**

In [ ]:
np.linspace(0.0, 1.0, num=5)

## Umformen eines Arrays (`reshape`)
* Die Array-Methode **`reshape`** wandelt einen Array in eine andere Dimension um;
* Die neue Form des Arrays muss die **gleiche Anzahl Elemente** wie das Original haben.

In [ ]:
np.arange(1, 21).reshape(4, 5)

## Anzeige grosser Arrays
* Wenn ein Array mehr als 1000 Elemente enthält, lässt NumPy die mittleren Zeilen, Spalten, oder beides bei der Ausgabe weg

In [ ]:
np.arange(1001)

In [ ]:
np.arange(2000).reshape(2, 1000)

In [ ]:
np.arange(1, 1201).reshape(6, 200)

In [ ]:
np.arange(1, 1401).reshape(7, 200)