In [1]:
import numpy as np
import numpy.linalg as la

In [2]:
M = np.array ([
    [ 2,  6, 2, 2],
    [-3, -8, 0, 2],
    [ 4,  9, 2, 3]
])
print (M)

[[ 2  6  2  2]
 [-3 -8  0  2]
 [ 4  9  2  3]]


In [3]:
A = M [:, 0:3]
print (A)

[[ 2  6  2]
 [-3 -8  0]
 [ 4  9  2]]


In [4]:
b = M [:, 3:4]
print (b)

[[2]
 [2]
 [3]]


In [5]:
E21 = np.array ([
    [  1, 0, 0],
    [3/2, 1, 0],
    [  0, 0, 1]
])
print (E21)

[[1.  0.  0. ]
 [1.5 1.  0. ]
 [0.  0.  1. ]]


In [6]:
E21 @ A

array([[2., 6., 2.],
       [0., 1., 3.],
       [4., 9., 2.]])

In [7]:
E31 = np.array ([
    [ 1, 0, 0],
    [ 0, 1, 0],
    [-2, 0, 1]
])
print (E31)

[[ 1  0  0]
 [ 0  1  0]
 [-2  0  1]]


In [8]:
E31 @ E21 @ A

array([[ 2.,  6.,  2.],
       [ 0.,  1.,  3.],
       [ 0., -3., -2.]])

In [9]:
E32 = np.array ([
    [1, 0, 0],
    [0, 1, 0],
    [0, 3, 1]
])
print (E32)

[[1 0 0]
 [0 1 0]
 [0 3 1]]


In [10]:
R = E32 @ E31 @ E21 @ A
print (R)

[[2. 6. 2.]
 [0. 1. 3.]
 [0. 0. 7.]]


In [11]:
L = la.inv (E21) @ la.inv (E31) @ la.inv (E32)
print (L)

[[ 1.   0.   0. ]
 [-1.5  1.   0. ]
 [ 2.  -3.   1. ]]


In [12]:
L @ R

array([[ 2.,  6.,  2.],
       [-3., -8.,  0.],
       [ 4.,  9.,  2.]])

In [13]:
L @ R - A

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])