In [1]:
import numpy as np
import numpy.linalg as la

In [2]:
M = np.array ([
    [ 3, -6, 0],
    [-2, 5, 1]
])
print (M)

[[ 3 -6  0]
 [-2  5  1]]


In [3]:
A = M [:, 0:2]
print (A)

[[ 3 -6]
 [-2  5]]


In [4]:
b = M [:, 2:3]
print (b)

[[0]
 [1]]


In [5]:
E21 = np.array ([
    [  1, 0],
    [2/3, 1]
])
print (E21)

[[1.         0.        ]
 [0.66666667 1.        ]]


In [6]:
R = E21 @ A
print (R)

[[ 3. -6.]
 [ 0.  1.]]


In [7]:
L = la.inv (E21)
print (L)

[[ 1.          0.        ]
 [-0.66666667  1.        ]]


In [8]:
L @ R

array([[ 3., -6.],
       [-2.,  5.]])

In [9]:
L @ R - A

array([[0., 0.],
       [0., 0.]])