In [1]:
import numpy as np
import numpy.linalg as la

In [2]:
M = np.array ([
    [2, -1,  3, 4,  9],
    [1,  0, -2, 7, 11],
    [3, -3,  1, 5,  8],
    [2,  1, 4 , 4, 10]
]) .astype (float)
print (M)

[[ 2. -1.  3.  4.  9.]
 [ 1.  0. -2.  7. 11.]
 [ 3. -3.  1.  5.  8.]
 [ 2.  1.  4.  4. 10.]]


In [3]:
A = M [0:4, 0:4]
print (A)

[[ 2. -1.  3.  4.]
 [ 1.  0. -2.  7.]
 [ 3. -3.  1.  5.]
 [ 2.  1.  4.  4.]]


In [4]:
b = M [0:4, 4:5]
print (b)

[[ 9.]
 [11.]
 [ 8.]
 [10.]]


In [5]:
R = A
print (R)

[[ 2. -1.  3.  4.]
 [ 1.  0. -2.  7.]
 [ 3. -3.  1.  5.]
 [ 2.  1.  4.  4.]]


In [6]:
f = R [1, 0] / R [0, 0]
E21 = np.array ([
    [ 1, 0, 0, 0],
    [-f, 1, 0, 0],
    [ 0, 0, 1, 0],
    [ 0, 0, 0, 1]
])
print (E21)
R = E21 @ R
print (R)

[[ 1.   0.   0.   0. ]
 [-0.5  1.   0.   0. ]
 [ 0.   0.   1.   0. ]
 [ 0.   0.   0.   1. ]]
[[ 2.  -1.   3.   4. ]
 [ 0.   0.5 -3.5  5. ]
 [ 3.  -3.   1.   5. ]
 [ 2.   1.   4.   4. ]]


In [7]:
f = R [2, 0] / R [0, 0]
E31 = np.array ([
    [ 1, 0, 0, 0],
    [ 0, 1, 0, 0],
    [-f, 0, 1, 0],
    [ 0, 0, 0, 1]
])
print (E31)
R = E31 @ R
print (R)

[[ 1.   0.   0.   0. ]
 [ 0.   1.   0.   0. ]
 [-1.5  0.   1.   0. ]
 [ 0.   0.   0.   1. ]]
[[ 2.  -1.   3.   4. ]
 [ 0.   0.5 -3.5  5. ]
 [ 0.  -1.5 -3.5 -1. ]
 [ 2.   1.   4.   4. ]]


In [8]:
f = R [3, 0] / R [0, 0]
E41 = np.array ([
    [ 1, 0, 0, 0],
    [ 0, 1, 0, 0],
    [ 0, 0, 1, 0],
    [-f, 0, 0, 1]
])
print (E41)
R = E41 @ R
print (R)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [-1.  0.  0.  1.]]
[[ 2.  -1.   3.   4. ]
 [ 0.   0.5 -3.5  5. ]
 [ 0.  -1.5 -3.5 -1. ]
 [ 0.   2.   1.   0. ]]


In [9]:
f = R [2, 1] / R [1, 1]
E32 = np.array ([
    [1,  0, 0, 0],
    [0,  1, 0, 0],
    [0, -f, 1, 0],
    [0,  0, 0, 1]
])
print (E32)
R = E32 @ R
print (R)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 3. 1. 0.]
 [0. 0. 0. 1.]]
[[  2.   -1.    3.    4. ]
 [  0.    0.5  -3.5   5. ]
 [  0.    0.  -14.   14. ]
 [  0.    2.    1.    0. ]]


In [10]:
f = R [3, 1] / R [1, 1]
E42 = np.array ([
    [1,  0, 0, 0],
    [0,  1, 0, 0],
    [0,  0, 1, 0],
    [0, -f, 0, 1]
])
print (E42)
R = E42 @ R
print (R)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0. -4.  0.  1.]]
[[  2.   -1.    3.    4. ]
 [  0.    0.5  -3.5   5. ]
 [  0.    0.  -14.   14. ]
 [  0.    0.   15.  -20. ]]


In [11]:
f = R [3, 2] / R [2, 2]
E43 = np.array ([
    [1, 0,  0, 0],
    [0, 1,  0, 0],
    [0, 0,  1, 0],
    [0, 0, -f, 1]
])
print (E43)
R = E43 @ R
print (R)

[[1.         0.         0.         0.        ]
 [0.         1.         0.         0.        ]
 [0.         0.         1.         0.        ]
 [0.         0.         1.07142857 1.        ]]
[[  2.   -1.    3.    4. ]
 [  0.    0.5  -3.5   5. ]
 [  0.    0.  -14.   14. ]
 [  0.    0.    0.   -5. ]]


In [12]:
L = la.inv (E21) @ la.inv (E31) @ la.inv (E41) @ la.inv (E32) @ la.inv (E42) @ la.inv (E43)
print (L)

[[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [ 1.5        -3.          1.          0.        ]
 [ 1.          4.         -1.07142857  1.        ]]


In [13]:
L @ R

array([[ 2., -1.,  3.,  4.],
       [ 1.,  0., -2.,  7.],
       [ 3., -3.,  1.,  5.],
       [ 2.,  1.,  4.,  4.]])

In [14]:
L @ R - A

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
y = la.solve (L, b)
print (y)

[[  9. ]
 [  6.5]
 [ 14. ]
 [-10. ]]


In [16]:
x = la.solve (R, y)
print (x)

[[-1.00000000e+00]
 [-1.33226763e-15]
 [ 1.00000000e+00]
 [ 2.00000000e+00]]


In [17]:
A @ x

array([[ 9.],
       [11.],
       [ 8.],
       [10.]])

In [18]:
A @ x - b

array([[ 0.00000000e+00],
       [ 1.77635684e-15],
       [-8.88178420e-16],
       [-1.77635684e-15]])