In [1]:
import numpy as np
import numpy.linalg as la

In [2]:
M = np.array ([
    [6, -1, -1,  4],
    [1,  1, 10, -6],
    [2, -1,  1, -2]
]) .astype (float)
print (M)

[[ 6. -1. -1.  4.]
 [ 1.  1. 10. -6.]
 [ 2. -1.  1. -2.]]


In [3]:
A = M [0:3, 0:3]
print (A)

[[ 6. -1. -1.]
 [ 1.  1. 10.]
 [ 2. -1.  1.]]


In [4]:
b = M [0:3, 3:4]
print (b)

[[ 4.]
 [-6.]
 [-2.]]


In [5]:
R = A
print (R)

[[ 6. -1. -1.]
 [ 1.  1. 10.]
 [ 2. -1.  1.]]


In [6]:
f = R [1, 0] / R [0, 0]
E21 = np.array ([
    [ 1, 0, 0],
    [-f, 1, 0],
    [ 0, 0, 1]
])
print (E21)
R = E21 @ R
print (R)

[[ 1.          0.          0.        ]
 [-0.16666667  1.          0.        ]
 [ 0.          0.          1.        ]]
[[ 6.         -1.         -1.        ]
 [ 0.          1.16666667 10.16666667]
 [ 2.         -1.          1.        ]]


In [7]:
f = R [2, 0] / R [0, 0]
E31 = np.array ([
    [ 1, 0, 0],
    [ 0, 1, 0],
    [-f, 0, 1]
])
print (E31)
R = E31 @ R
print (R)

[[ 1.          0.          0.        ]
 [ 0.          1.          0.        ]
 [-0.33333333  0.          1.        ]]
[[ 6.         -1.         -1.        ]
 [ 0.          1.16666667 10.16666667]
 [ 0.         -0.66666667  1.33333333]]


In [8]:
f = R [2, 1] / R [1, 1]
E32 = np.array ([
    [1,  0, 0],
    [0,  1, 0],
    [0, -f, 1]
])
print (E32)
R = E32 @ R
print (R)

[[1.         0.         0.        ]
 [0.         1.         0.        ]
 [0.         0.57142857 1.        ]]
[[ 6.00000000e+00 -1.00000000e+00 -1.00000000e+00]
 [ 0.00000000e+00  1.16666667e+00  1.01666667e+01]
 [ 0.00000000e+00  1.11022302e-16  7.14285714e+00]]


In [9]:
L = la.inv (E21) @ la.inv (E31) @ la.inv (E32)
print (L)

[[ 1.          0.          0.        ]
 [ 0.16666667  1.          0.        ]
 [ 0.33333333 -0.57142857  1.        ]]


In [10]:
L @ R

array([[ 6., -1., -1.],
       [ 1.,  1., 10.],
       [ 2., -1.,  1.]])

In [11]:
L @ R - A

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
y = la.solve (L, b)
print (y)

[[ 4.        ]
 [-6.66666667]
 [-7.14285714]]


In [13]:
x = la.solve (R, y)
print (x)

[[ 1.]
 [ 3.]
 [-1.]]


In [14]:
A @ x

array([[ 4.],
       [-6.],
       [-2.]])

In [15]:
A @ x - b

array([[ 0.00000000e+00],
       [-8.88178420e-16],
       [ 6.66133815e-16]])