In [1]:
import numpy as np
import numpy.linalg as la

In [2]:
M = np.array ([
    [ 1,  1, 2,  8],
    [-1, -2, 3,  1],
    [ 3, -7, 4, 10]
]) .astype (float)
print (M)

[[ 1.  1.  2.  8.]
 [-1. -2.  3.  1.]
 [ 3. -7.  4. 10.]]


In [3]:
A = M [0:3, 0:3]
print (A)

[[ 1.  1.  2.]
 [-1. -2.  3.]
 [ 3. -7.  4.]]


In [4]:
b = M [0:3, 3:4]
print (b)

[[ 8.]
 [ 1.]
 [10.]]


In [5]:
R = A
print (R)

[[ 1.  1.  2.]
 [-1. -2.  3.]
 [ 3. -7.  4.]]


In [6]:
f = R [1, 0] / R [0, 0]
E21 = np.array ([
    [ 1, 0, 0],
    [-f, 1, 0],
    [ 0, 0, 1]
])
print (E21)
R = E21 @ R
print (R)

[[1. 0. 0.]
 [1. 1. 0.]
 [0. 0. 1.]]
[[ 1.  1.  2.]
 [ 0. -1.  5.]
 [ 3. -7.  4.]]


In [7]:
f = R [2, 0] / R [0, 0]
E31 = np.array ([
    [ 1, 0, 0],
    [ 0, 1, 0],
    [-f, 0, 1]
])
print (E31)
R = E31 @ R
print (R)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [-3.  0.  1.]]
[[  1.   1.   2.]
 [  0.  -1.   5.]
 [  0. -10.  -2.]]


In [8]:
f = R [2, 1] / R [1, 1]
E32 = np.array ([
    [1,  0, 0],
    [0,  1, 0],
    [0, -f, 1]
])
print (E32)
R = E32 @ R
print (R)

[[  1.   0.   0.]
 [  0.   1.   0.]
 [  0. -10.   1.]]
[[  1.   1.   2.]
 [  0.  -1.   5.]
 [  0.   0. -52.]]


In [9]:
L = la.inv (E21) @ la.inv (E31) @ la.inv (E32)
print (L)

[[ 1.  0.  0.]
 [-1.  1.  0.]
 [ 3. 10.  1.]]


In [10]:
L @ R

array([[ 1.,  1.,  2.],
       [-1., -2.,  3.],
       [ 3., -7.,  4.]])

In [11]:
L @ R - A

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
y = la.solve (L, b)
print (y)

[[   8.]
 [   9.]
 [-104.]]


In [13]:
x = la.solve (R, y)
print (x)

[[3.]
 [1.]
 [2.]]


In [14]:
A @ x

array([[ 8.],
       [ 1.],
       [10.]])

In [15]:
A @ x - b

array([[ 1.77635684e-15],
       [-5.32907052e-15],
       [-7.10542736e-15]])