# Multiplikation zweier Matrizen

In [2]:
import numpy as np

A = np.array([
    [4, -2, -2, 0],
    [-2, -7, 3, 8],
    [0, 1, -2, -1]
])
B = np.array([
    [4, -5],
    [3, -1],
    [6, 4],
    [0, -3]
])
A @ B

array([[ -2, -26],
       [-11,   5],
       [ -9,  -6]])

In [6]:
import numpy as np

B = np.array([
    [1, 2],
    [2, 4]
])
np.linalg.inv(B)

LinAlgError: Singular matrix

### Eliminationsmatrix

In [19]:
import numpy as np
import numpy.linalg as la

A = np.array([
    [1, 2, 1],
    [2, 1, 0],
    [-3, 0, 9]
])

E21 = np.array([
    [1, 0, 0],
    [-2, 1, 0],
    [0, 0, 1]
])
E21 @ A

E31 = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [3, 0, 1]
])
E31 @ E21 @ A

E32 = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 2, 1]
])
R = E32 @ E31 @ E21 @ A

In [17]:
L = la.inv(E21) @ la.inv(E31) @ la.inv(E32)
print(L)

[[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-3. -2.  1.]]


In [20]:
L @ R

array([[ 1.,  2.,  1.],
       [ 2.,  1.,  0.],
       [-3.,  0.,  9.]])